let IslamicTerrorist: Sprite = null
let mySprite = sprites.create(img`
    ....................
    ....................
    ......ffff..........
    .....fdddd..........
    .....fdfdf..........
    .....fddddd.........
    ......dfdd..........
    .......dff....1.....
    ...8888111222.11....
    ...dd8811122d.11....
    ...ddd811122ddf.....
    ...ddd811122ddf.....
    .....8811122........
    .....8811122........
    .....fffffff........
    .....88...22........
    .....88...22........
    .....88...22........
    .....ff...ff........
    .....fff..fff.......
    .....fff..fff.......
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Player)
tiles.setTilemap(tilemap`level1`)
scene.cameraFollowSprite(mySprite)
controller.moveSprite(mySprite, 100, 100)
game.onUpdate(function () {
    IslamicTerrorist = sprites.create(img`
        ................
        ..........dddd..
        .........dddddd.
        .........fefefd.
        .........fffffd.
        .........dddddd.
        .........dddddd.
        fffff..ee22ee22e
        fffff..ee22ff22e
        ..cffeeeeffddffe
        ...ffeeee22ee22e
        ........e22ff22e
        ........edddddde
        ........eeeeeeee
        .........ffffff.
        .........dd..dd.
        .........ff..ff.
        .........ee..ee.
        .........ff..ff.
        ........fff.fff.
        `, SpriteKind.Enemy)
})
